storage_dir: ~/.local/bin/AppImages
symlink_dir: ~/.local/bin
naming_format: '{name}.AppImage'
manage_desktop_files: true
create_symlinks: false
segmented_downloads: true
respect_rate_limits: true
github_proxy: false
github_proxy_prefix: https://gh-proxy.com/
